version: '2.1'
services:
  app:
    entrypoint: 'npm run dev'
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "80:80"
    environment:
      - PORT=80
      - NODE_ENV=dev
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_DB=dev
    volumes:
      - ".:/src"
      - "/src/node_modules"
  postgres:
    environment:
      - POSTGRES_DB=dev
