version: '2.1'

services:
  app:
    build:
      context: .
      args:
        - NPM_TOKEN
    environment:
      - NPM_TOKEN
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "80:80"

  postgres:
    image: postgres:9.6
    container_name: postgres-koa-template
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 30s
      retries: 50
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
