version: '2.1'
services:
  app:
    entrypoint: 'npm run watch'
    ports:
      - "80:80"
    environment:
      - PORT=80
      - NODE_ENV=test
  postgres:
    environment:
      - POSTGRES_DB=test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local -d test"]
      interval: 1s
      timeout: 30s
      retries: 50
